create schema `mimic-four-ml4219.x_mimiciv_hosp` ;
create schema `mimic-four-ml4219.x_mimiciv_icu` ;
create schema `mimic-four-ml4219.x_mimiciv_derived` ;
create schema `mimic-four-ml4219.x_ED` ;
create schema `mimic-four-ml4219.x_note` ;


create table  `your-project-id1234.x_mimiciv_hosp.admissions` as	SELECT * FROM `physionet-data.mimiciv_hosp.admissions` 				;
create table  `your-project-id1234.x_mimiciv_hosp.d_hcpcs` as	SELECT * FROM `physionet-data.mimiciv_hosp.d_hcpcs` 				;
create table  `your-project-id1234.x_mimiciv_hosp.d_icd_diagnoses` as	SELECT * FROM `physionet-data.mimiciv_hosp.d_icd_diagnoses` 				;
create table  `your-project-id1234.x_mimiciv_hosp.d_icd_procedures` as	SELECT * FROM `physionet-data.mimiciv_hosp.d_icd_procedures` 				;
create table  `your-project-id1234.x_mimiciv_hosp.d_labitems` as	SELECT * FROM `physionet-data.mimiciv_hosp.d_labitems` 				;
create table  `your-project-id1234.x_mimiciv_hosp.diagnoses_icd` as	SELECT * FROM `physionet-data.mimiciv_hosp.diagnoses_icd` 				;
create table  `your-project-id1234.x_mimiciv_hosp.drgcodes` as	SELECT * FROM `physionet-data.mimiciv_hosp.drgcodes` 				;
create table  `your-project-id1234.x_mimiciv_hosp.emar` as	SELECT * FROM `physionet-data.mimiciv_hosp.emar` 				;
create table  `your-project-id1234.x_mimiciv_hosp.emar_detail` as	SELECT * FROM `physionet-data.mimiciv_hosp.emar_detail` 				;
create table  `your-project-id1234.x_mimiciv_hosp.hcpcsevents` as	SELECT * FROM `physionet-data.mimiciv_hosp.hcpcsevents` 				;
create table  `your-project-id1234.x_mimiciv_hosp.labevents` as	SELECT * FROM `physionet-data.mimiciv_hosp.labevents` 				;
create table  `your-project-id1234.x_mimiciv_hosp.microbiologyevents` as	SELECT * FROM `physionet-data.mimiciv_hosp.microbiologyevents` 				;
create table  `your-project-id1234.x_mimiciv_hosp.omr` as	SELECT * FROM `physionet-data.mimiciv_hosp.omr` 				;
create table  `your-project-id1234.x_mimiciv_hosp.patients` as	SELECT * FROM `physionet-data.mimiciv_hosp.patients` 				;
create table  `your-project-id1234.x_mimiciv_hosp.pharmacy` as	SELECT * FROM `physionet-data.mimiciv_hosp.pharmacy` 				;
create table  `your-project-id1234.x_mimiciv_hosp.poe` as	SELECT * FROM `physionet-data.mimiciv_hosp.poe` 				;
create table  `your-project-id1234.x_mimiciv_hosp.poe_detail` as	SELECT * FROM `physionet-data.mimiciv_hosp.poe_detail` 				;
create table  `your-project-id1234.x_mimiciv_hosp.prescriptions` as	SELECT * FROM `physionet-data.mimiciv_hosp.prescriptions` 				;
create table  `your-project-id1234.x_mimiciv_hosp.procedures_icd` as	SELECT * FROM `physionet-data.mimiciv_hosp.procedures_icd` 				;
create table  `your-project-id1234.x_mimiciv_hosp.provider` as	SELECT * FROM `physionet-data.mimiciv_hosp.provider` 				;
create table  `your-project-id1234.x_mimiciv_hosp.services` as	SELECT * FROM `physionet-data.mimiciv_hosp.services` 				;
create table  `your-project-id1234.x_mimiciv_hosp.transfers` as	SELECT * FROM `physionet-data.mimiciv_hosp.transfers` 				;
					
create table  `your-project-id1234.x_mimiciv_icu.caregiver` as	SELECT * FROM `physionet-data.mimiciv_icu.caregiver` 				;
create table  `your-project-id1234.x_mimiciv_icu.chartevents` as	SELECT * FROM `physionet-data.mimiciv_icu.chartevents` 				;
create table  `your-project-id1234.x_mimiciv_icu.d_items` as	SELECT * FROM `physionet-data.mimiciv_icu.d_items` 				;
create table  `your-project-id1234.x_mimiciv_icu.datetimeevents` as	SELECT * FROM `physionet-data.mimiciv_icu.datetimeevents` 				;
create table  `your-project-id1234.x_mimiciv_icu.icustays` as	SELECT * FROM `physionet-data.mimiciv_icu.icustays` 				;
create table  `your-project-id1234.x_mimiciv_icu.ingredientevents` as	SELECT * FROM `physionet-data.mimiciv_icu.ingredientevents` 				;
create table  `your-project-id1234.x_mimiciv_icu.inputevents` as	SELECT * FROM `physionet-data.mimiciv_icu.inputevents` 				;
create table  `your-project-id1234.x_mimiciv_icu.outputevents` as	SELECT * FROM `physionet-data.mimiciv_icu.outputevents` 				;
create table  `your-project-id1234.x_mimiciv_icu.procedureevents` as	SELECT * FROM `physionet-data.mimiciv_icu.procedureevents` 				;

create table  `your-project-id1234.x_mimiciv_derived.acei` as	SELECT * FROM `physionet-data.mimiciv_derived.acei` 				;
create table  `your-project-id1234.x_mimiciv_derived.age` as	SELECT * FROM `physionet-data.mimiciv_derived.age` 				;
create table  `your-project-id1234.x_mimiciv_derived.antibiotic` as	SELECT * FROM `physionet-data.mimiciv_derived.antibiotic` 				;
create table  `your-project-id1234.x_mimiciv_derived.apsiii` as	SELECT * FROM `physionet-data.mimiciv_derived.apsiii` 				;
create table  `your-project-id1234.x_mimiciv_derived.arb` as	SELECT * FROM `physionet-data.mimiciv_derived.arb` 				;
create table  `your-project-id1234.x_mimiciv_derived.bg` as	SELECT * FROM `physionet-data.mimiciv_derived.bg` 				;
create table  `your-project-id1234.x_mimiciv_derived.blood_differential` as	SELECT * FROM `physionet-data.mimiciv_derived.blood_differential` 				;
create table  `your-project-id1234.x_mimiciv_derived.cardiac_marker` as	SELECT * FROM `physionet-data.mimiciv_derived.cardiac_marker` 				;
create table  `your-project-id1234.x_mimiciv_derived.charlson` as	SELECT * FROM `physionet-data.mimiciv_derived.charlson` 				;
create table  `your-project-id1234.x_mimiciv_derived.chemistry` as	SELECT * FROM `physionet-data.mimiciv_derived.chemistry` 				;
create table  `your-project-id1234.x_mimiciv_derived.coagulation` as	SELECT * FROM `physionet-data.mimiciv_derived.coagulation` 				;
create table  `your-project-id1234.x_mimiciv_derived.code_status` as	SELECT * FROM `physionet-data.mimiciv_derived.code_status` 				;
create table  `your-project-id1234.x_mimiciv_derived.complete_blood_count` as	SELECT * FROM `physionet-data.mimiciv_derived.complete_blood_count` 				;
create table  `your-project-id1234.x_mimiciv_derived.creatinine_baseline` as	SELECT * FROM `physionet-data.mimiciv_derived.creatinine_baseline` 				;
create table  `your-project-id1234.x_mimiciv_derived.crrt` as	SELECT * FROM `physionet-data.mimiciv_derived.crrt` 				;
create table  `your-project-id1234.x_mimiciv_derived.differential_detailed` as	SELECT * FROM `physionet-data.mimiciv_derived.differential_detailed` 				;
create table  `your-project-id1234.x_mimiciv_derived.dobutamine` as	SELECT * FROM `physionet-data.mimiciv_derived.dobutamine` 				;
create table  `your-project-id1234.x_mimiciv_derived.dopamine` as	SELECT * FROM `physionet-data.mimiciv_derived.dopamine` 				;
create table  `your-project-id1234.x_mimiciv_derived.enzyme` as	SELECT * FROM `physionet-data.mimiciv_derived.enzyme` 				;
create table  `your-project-id1234.x_mimiciv_derived.epinephrine` as	SELECT * FROM `physionet-data.mimiciv_derived.epinephrine` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_bg` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_bg` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_bg_art` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_bg_art` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_gcs` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_gcs` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_height` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_height` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_lab` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_lab` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_rrt` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_rrt` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_sofa` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_sofa` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_urine_output` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_urine_output` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_vitalsign` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_vitalsign` 				;
create table  `your-project-id1234.x_mimiciv_derived.first_day_weight` as	SELECT * FROM `physionet-data.mimiciv_derived.first_day_weight` 				;
create table  `your-project-id1234.x_mimiciv_derived.gcs` as	SELECT * FROM `physionet-data.mimiciv_derived.gcs` 				;
create table  `your-project-id1234.x_mimiciv_derived.height` as	SELECT * FROM `physionet-data.mimiciv_derived.height` 				;
create table  `your-project-id1234.x_mimiciv_derived.icp` as	SELECT * FROM `physionet-data.mimiciv_derived.icp` 				;
create table  `your-project-id1234.x_mimiciv_derived.icustay_detail` as	SELECT * FROM `physionet-data.mimiciv_derived.icustay_detail` 				;
create table  `your-project-id1234.x_mimiciv_derived.icustay_hourly` as	SELECT * FROM `physionet-data.mimiciv_derived.icustay_hourly` 				;
create table  `your-project-id1234.x_mimiciv_derived.icustay_times` as	SELECT * FROM `physionet-data.mimiciv_derived.icustay_times` 				;
create table  `your-project-id1234.x_mimiciv_derived.inflammation` as	SELECT * FROM `physionet-data.mimiciv_derived.inflammation` 				;
create table  `your-project-id1234.x_mimiciv_derived.invasive_line` as	SELECT * FROM `physionet-data.mimiciv_derived.invasive_line` 				;
create table  `your-project-id1234.x_mimiciv_derived.kdigo_creatinine` as	SELECT * FROM `physionet-data.mimiciv_derived.kdigo_creatinine` 				;
create table  `your-project-id1234.x_mimiciv_derived.kdigo_stages` as	SELECT * FROM `physionet-data.mimiciv_derived.kdigo_stages` 				;
create table  `your-project-id1234.x_mimiciv_derived.kdigo_uo` as	SELECT * FROM `physionet-data.mimiciv_derived.kdigo_uo` 				;
create table  `your-project-id1234.x_mimiciv_derived.lods` as	SELECT * FROM `physionet-data.mimiciv_derived.lods` 				;
create table  `your-project-id1234.x_mimiciv_derived.meld` as	SELECT * FROM `physionet-data.mimiciv_derived.meld` 				;
create table  `your-project-id1234.x_mimiciv_derived.milrinone` as	SELECT * FROM `physionet-data.mimiciv_derived.milrinone` 				;
create table  `your-project-id1234.x_mimiciv_derived.neuroblock` as	SELECT * FROM `physionet-data.mimiciv_derived.neuroblock` 				;
create table  `your-project-id1234.x_mimiciv_derived.norepinephrine` as	SELECT * FROM `physionet-data.mimiciv_derived.norepinephrine` 				;
create table  `your-project-id1234.x_mimiciv_derived.norepinephrine_equivalent_dose` as	SELECT * FROM `physionet-data.mimiciv_derived.norepinephrine_equivalent_dose` 				;
create table  `your-project-id1234.x_mimiciv_derived.nsaid` as	SELECT * FROM `physionet-data.mimiciv_derived.nsaid` 				;
create table  `your-project-id1234.x_mimiciv_derived.oasis` as	SELECT * FROM `physionet-data.mimiciv_derived.oasis` 				;
create table  `your-project-id1234.x_mimiciv_derived.oxygen_delivery` as	SELECT * FROM `physionet-data.mimiciv_derived.oxygen_delivery` 				;
create table  `your-project-id1234.x_mimiciv_derived.phenylephrine` as	SELECT * FROM `physionet-data.mimiciv_derived.phenylephrine` 				;
create table  `your-project-id1234.x_mimiciv_derived.rhythm` as	SELECT * FROM `physionet-data.mimiciv_derived.rhythm` 				;
create table  `your-project-id1234.x_mimiciv_derived.rrt` as	SELECT * FROM `physionet-data.mimiciv_derived.rrt` 				;
create table  `your-project-id1234.x_mimiciv_derived.sapsii` as	SELECT * FROM `physionet-data.mimiciv_derived.sapsii` 				;
create table  `your-project-id1234.x_mimiciv_derived.sepsis3` as	SELECT * FROM `physionet-data.mimiciv_derived.sepsis3` 				;
create table  `your-project-id1234.x_mimiciv_derived.sirs` as	SELECT * FROM `physionet-data.mimiciv_derived.sirs` 				;
create table  `your-project-id1234.x_mimiciv_derived.sofa` as	SELECT * FROM `physionet-data.mimiciv_derived.sofa` 				;
create table  `your-project-id1234.x_mimiciv_derived.suspicion_of_infection` as	SELECT * FROM `physionet-data.mimiciv_derived.suspicion_of_infection` 				;
create table  `your-project-id1234.x_mimiciv_derived.urine_output` as	SELECT * FROM `physionet-data.mimiciv_derived.urine_output` 				;
create table  `your-project-id1234.x_mimiciv_derived.urine_output_rate` as	SELECT * FROM `physionet-data.mimiciv_derived.urine_output_rate` 				;
create table  `your-project-id1234.x_mimiciv_derived.vasoactive_agent` as	SELECT * FROM `physionet-data.mimiciv_derived.vasoactive_agent` 				;
create table  `your-project-id1234.x_mimiciv_derived.vasopressin` as	SELECT * FROM `physionet-data.mimiciv_derived.vasopressin` 				;
create table  `your-project-id1234.x_mimiciv_derived.ventilation` as	SELECT * FROM `physionet-data.mimiciv_derived.ventilation` 				;
create table  `your-project-id1234.x_mimiciv_derived.ventilator_setting` as	SELECT * FROM `physionet-data.mimiciv_derived.ventilator_setting` 				;
create table  `your-project-id1234.x_mimiciv_derived.vitalsign` as	SELECT * FROM `physionet-data.mimiciv_derived.vitalsign` 				;
create table  `your-project-id1234.x_mimiciv_derived.weight_durations` as	SELECT * FROM `physionet-data.mimiciv_derived.weight_durations` 				;


create table  `your-project-id1234.x_ED.diagnosis` as	SELECT * FROM `physionet-data.mimiciv_ed.diagnosis` 				;
create table  `your-project-id1234.x_ED.edstays` as	SELECT * FROM `physionet-data.mimiciv_ed.edstays` 				;
create table  `your-project-id1234.x_ED.medrecon` as	SELECT * FROM `physionet-data.mimiciv_ed.medrecon` 				;
create table  `your-project-id1234.x_ED.pyxis` as	SELECT * FROM `physionet-data.mimiciv_ed.pyxis` 				;
create table  `your-project-id1234.x_ED.triage` as	SELECT * FROM `physionet-data.mimiciv_ed.triage` 				;
create table  `your-project-id1234.x_ED.vitalsign` as	SELECT * FROM `physionet-data.mimiciv_ed.vitalsign` 				;



create table  `your-project-id1234.x_note.discharge` as	SELECT * FROM `physionet-data.mimiciv_note.discharge` 				;
create table  `your-project-id1234.x_note.discharge_detail` as	SELECT * FROM `physionet-data.mimiciv_note.discharge_detail` 				;
create table  `your-project-id1234.x_note.radiology` as	SELECT * FROM `physionet-data.mimiciv_note.radiology` 				;
create table  `your-project-id1234.x_note.radiology_detail` as	SELECT * FROM `physionet-data.mimiciv_note.radiology_detail` 				;


