import os
from google.cloud import bigquery

symPath = '../gcKey/CEKG.json'
Realpath = os.path.realpath(symPath)
print(Realpath)

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = Realpath

client = bigquery.Client()

# Perform a query.
query1 = f'''            


create schema `your-project-id1234.R_TimeA` ;


create table `your-project-id1234.R_TimeA.Table001` as SELECT subject_id, hadm_id, edregtime   as Timestamp FROM `your-project-id1234.S_Admission.2_Admissions`  where edregtime is not null ;  
create table `your-project-id1234.R_TimeA.Table002` as SELECT subject_id, hadm_id, admittime as Timestamp FROM `your-project-id1234.S_Admission.2_Admissions`  where admittime is not null ;  
create table `your-project-id1234.R_TimeA.Table003` as SELECT subject_id, hadm_id, edouttime  as Timestamp FROM `your-project-id1234.S_Admission.2_Admissions`  where edouttime is not null ;  
create table `your-project-id1234.R_TimeA.Table004` as SELECT subject_id, hadm_id, dischtime as Timestamp FROM `your-project-id1234.S_Admission.2_Admissions`  where dischtime is not null ;  
create table `your-project-id1234.R_TimeA.Table005` as SELECT subject_id, hadm_id, deathtime as Timestamp FROM `your-project-id1234.S_Admission.2_Admissions`  where deathtime is not null ;  
create table `your-project-id1234.R_TimeA.Table006` as SELECT subject_id, hadm_id, chartdate as Timestamp FROM `your-project-id1234.S_cptEvent.1_cptEvents`  where chartdate is not null ;  
create table `your-project-id1234.R_TimeA.Table007` as SELECT subject_id, hadm_id, chartdate as Timestamp FROM `your-project-id1234.S_icd_procedures.1_icdPCM`  where chartdate is not null ;  
create table `your-project-id1234.R_TimeA.Table008` as SELECT subject_id, hadm_id, charttime  as Timestamp FROM `your-project-id1234.S_eMAR.1_eMAR`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table009` as SELECT subject_id, hadm_id, scheduletime as Timestamp FROM `your-project-id1234.S_eMAR.1_eMAR`  where scheduletime is not null ;  
create table `your-project-id1234.R_TimeA.Table010` as SELECT subject_id, hadm_id, storetime as Timestamp FROM `your-project-id1234.S_eMAR.1_eMAR`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table011` as SELECT subject_id, hadm_id, chartdate  as Timestamp FROM `your-project-id1234.S_Microbiology.1_Microbiology`  where chartdate is not null ;  
create table `your-project-id1234.R_TimeA.Table012` as SELECT subject_id, hadm_id, charttime  as Timestamp FROM `your-project-id1234.S_Microbiology.1_Microbiology`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table013` as SELECT subject_id, hadm_id, storedate as Timestamp FROM `your-project-id1234.S_Microbiology.1_Microbiology`  where storedate is not null ;  
create table `your-project-id1234.R_TimeA.Table014` as SELECT subject_id, hadm_id, storetime as Timestamp FROM `your-project-id1234.S_Microbiology.1_Microbiology`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table015` as SELECT subject_id, chartdate as Timestamp FROM `your-project-id1234.S_OMR.1_OMR`  where chartdate is not null ;  
create table `your-project-id1234.R_TimeA.Table016` as SELECT subject_id, dod as Timestamp FROM `your-project-id1234.S_Patients.1_Patient`  where dod is not null ;  
create table `your-project-id1234.R_TimeA.Table017` as SELECT subject_id, hadm_id, starttime as Timestamp FROM `your-project-id1234.S_pharmacy.1_pharmacy`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table018` as SELECT subject_id, hadm_id, stoptime as Timestamp FROM `your-project-id1234.S_pharmacy.1_pharmacy`  where stoptime is not null ;  
create table `your-project-id1234.R_TimeA.Table019` as SELECT subject_id, hadm_id, entertime as Timestamp FROM `your-project-id1234.S_pharmacy.1_pharmacy`  where entertime is not null ;  
create table `your-project-id1234.R_TimeA.Table020` as SELECT subject_id, hadm_id, verifiedtime as Timestamp FROM `your-project-id1234.S_pharmacy.1_pharmacy`  where verifiedtime is not null ;  
create table `your-project-id1234.R_TimeA.Table021` as SELECT subject_id, hadm_id, ordertime as Timestamp FROM `your-project-id1234.S_poe.1_POE`  where ordertime is not null ;  
create table `your-project-id1234.R_TimeA.Table022` as SELECT subject_id, hadm_id, charttime  as Timestamp FROM `your-project-id1234.S_labEvents.2_Blood_Gas`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table023` as SELECT subject_id, hadm_id, storetime as Timestamp FROM `your-project-id1234.S_labEvents.2_Blood_Gas`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table024` as SELECT subject_id, hadm_id, charttime  as Timestamp FROM `your-project-id1234.S_labEvents.2_Chemistry`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table025` as SELECT subject_id, hadm_id, storetime as Timestamp FROM `your-project-id1234.S_labEvents.2_Chemistry`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table026` as SELECT subject_id, hadm_id, charttime  as Timestamp FROM `your-project-id1234.S_labEvents.2_Hematology`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table027` as SELECT subject_id, hadm_id, storetime as Timestamp FROM `your-project-id1234.S_labEvents.2_Hematology`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table028` as SELECT subject_id, hadm_id, transfertime as Timestamp FROM `your-project-id1234.S_Services.1_Service`  where transfertime is not null ;  
create table `your-project-id1234.R_TimeA.Table029` as SELECT subject_id, hadm_id, transfer_id, intime as Timestamp FROM `your-project-id1234.S_Transfers.1_Transfer`  where intime is not null ;  
create table `your-project-id1234.R_TimeA.Table030` as SELECT subject_id, hadm_id, transfer_id, outtime as Timestamp FROM `your-project-id1234.S_Transfers.1_Transfer`  where outtime is not null ;  
create table `your-project-id1234.R_TimeA.Table031` as SELECT subject_id, hadm_id, starttime as Timestamp FROM `your-project-id1234.S_prescriptions.1_prescriptions`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table032` as SELECT subject_id, hadm_id, stoptime as Timestamp FROM `your-project-id1234.S_prescriptions.1_prescriptions`  where stoptime is not null ;  
create table `your-project-id1234.R_TimeA.Table033` as SELECT subject_id, hadm_id, stay_id, charttime as Timestamp FROM `your-project-id1234.S_chartEvents.1_chartEvent`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table034` as SELECT subject_id, hadm_id, stay_id, storetime as Timestamp FROM `your-project-id1234.S_chartEvents.1_chartEvent`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table035` as SELECT subject_id, hadm_id, stay_id, charttime as Timestamp FROM `your-project-id1234.S_datetimeEvents.1_datetimeEvent`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table036` as SELECT subject_id, hadm_id, stay_id, storetime as Timestamp FROM `your-project-id1234.S_datetimeEvents.1_datetimeEvent`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table037` as SELECT subject_id, hadm_id, stay_id, value as Timestamp FROM `your-project-id1234.S_datetimeEvents.1_datetimeEvent`  where value is not null ;  
create table `your-project-id1234.R_TimeA.Table038` as SELECT subject_id, hadm_id, stay_id, intime as Timestamp FROM `your-project-id1234.S_icuStays.1_icuStays`  where intime is not null ;  
create table `your-project-id1234.R_TimeA.Table039` as SELECT subject_id, hadm_id, stay_id, outtime as Timestamp FROM `your-project-id1234.S_icuStays.1_icuStays`  where outtime is not null ;  
create table `your-project-id1234.R_TimeA.Table040` as SELECT subject_id, hadm_id, stay_id, starttime as Timestamp FROM `your-project-id1234.S_ingredientEvents.1_ingredientEvent`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table041` as SELECT subject_id, hadm_id, stay_id, endtime as Timestamp FROM `your-project-id1234.S_ingredientEvents.1_ingredientEvent`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table042` as SELECT subject_id, hadm_id, stay_id, storetime as Timestamp FROM `your-project-id1234.S_ingredientEvents.1_ingredientEvent`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table043` as SELECT subject_id, hadm_id, stay_id, starttime as Timestamp FROM `your-project-id1234.S_inputEvents.1_inputEvent`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table044` as SELECT subject_id, hadm_id, stay_id, endtime as Timestamp FROM `your-project-id1234.S_inputEvents.1_inputEvent`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table045` as SELECT subject_id, hadm_id, stay_id, storetime as Timestamp FROM `your-project-id1234.S_inputEvents.1_inputEvent`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table046` as SELECT subject_id, hadm_id, stay_id, charttime as Timestamp FROM `your-project-id1234.S_outputEvents.1_outputEvent`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table047` as SELECT subject_id, hadm_id, stay_id, storetime as Timestamp FROM `your-project-id1234.S_outputEvents.1_outputEvent`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table048` as SELECT subject_id, hadm_id, stay_id, starttime as Timestamp FROM `your-project-id1234.S_procedureEvents.1_procedureEvent`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table049` as SELECT subject_id, hadm_id, stay_id, endtime as Timestamp FROM `your-project-id1234.S_procedureEvents.1_procedureEvent`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table050` as SELECT subject_id, hadm_id, stay_id, storetime as Timestamp FROM `your-project-id1234.S_procedureEvents.1_procedureEvent`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table051` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_note.discharge`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table052` as SELECT subject_id, hadm_id, storetime as Timestamp FROM `your-project-id1234.x_note.discharge`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table053` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_note.radiology`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table054` as SELECT subject_id, hadm_id, storetime as Timestamp FROM `your-project-id1234.x_note.radiology`  where storetime is not null ;  
create table `your-project-id1234.R_TimeA.Table055` as SELECT subject_id, hadm_id, stay_id, intime as Timestamp FROM `your-project-id1234.x_ED.edstays`  where intime is not null ;  
create table `your-project-id1234.R_TimeA.Table056` as SELECT subject_id, hadm_id, stay_id, outtime as Timestamp FROM `your-project-id1234.x_ED.edstays`  where outtime is not null ;  
create table `your-project-id1234.R_TimeA.Table057` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_ED.medrecon`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table058` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_ED.pyxis`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table059` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_ED.vitalsign`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table060` as SELECT subject_id, hadm_id, admittime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.age`  where admittime is not null ;  
create table `your-project-id1234.R_TimeA.Table061` as SELECT subject_id, hadm_id, stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.antibiotic`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table062` as SELECT subject_id, hadm_id, stay_id, stoptime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.antibiotic`  where stoptime is not null ;  
create table `your-project-id1234.R_TimeA.Table063` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.bg`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table064` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.blood_differential`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table065` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.cardiac_marker`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table066` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.chemistry`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table067` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.coagulation`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table068` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.complete_blood_count`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table069` as SELECT stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.crrt`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table070` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.differential_detailed`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table071` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.dobutamine`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table072` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.dobutamine`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table073` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.dopamine`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table074` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.dopamine`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table075` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.enzyme`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table076` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.epinephrine`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table077` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.epinephrine`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table078` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.gcs`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table079` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.height`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table080` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icp`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table081` as SELECT subject_id, dod as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icustay_detail`  where dod is not null ;  
create table `your-project-id1234.R_TimeA.Table082` as SELECT subject_id, hadm_id, stay_id, admittime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icustay_detail`  where admittime is not null ;  
create table `your-project-id1234.R_TimeA.Table083` as SELECT subject_id, hadm_id, stay_id, dischtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icustay_detail`  where dischtime is not null ;  
create table `your-project-id1234.R_TimeA.Table084` as SELECT subject_id, hadm_id, stay_id, icu_intime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icustay_detail`  where icu_intime is not null ;  
create table `your-project-id1234.R_TimeA.Table085` as SELECT subject_id, hadm_id, stay_id, icu_outtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icustay_detail`  where icu_outtime is not null ;  
create table `your-project-id1234.R_TimeA.Table086` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icustay_hourly`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table087` as SELECT subject_id, hadm_id, stay_id, intime_hr as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icustay_times`  where intime_hr is not null ;  
create table `your-project-id1234.R_TimeA.Table088` as SELECT subject_id, hadm_id, stay_id, outtime_hr as Timestamp FROM `your-project-id1234.x_mimiciv_derived.icustay_times`  where outtime_hr is not null ;  
create table `your-project-id1234.R_TimeA.Table089` as SELECT subject_id, hadm_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.inflammation`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table090` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.invasive_line`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table091` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.invasive_line`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table092` as SELECT hadm_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.kdigo_creatinine`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table093` as SELECT subject_id, hadm_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.kdigo_stages`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table094` as SELECT stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.kdigo_uo`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table095` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.milrinone`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table096` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.milrinone`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table097` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.neuroblock`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table098` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.neuroblock`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table099` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.norepinephrine`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table100` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.norepinephrine`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table101` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.norepinephrine_equivalent_dose`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table102` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.norepinephrine_equivalent_dose`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table103` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.oxygen_delivery`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table104` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.phenylephrine`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table105` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.phenylephrine`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table106` as SELECT subject_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.rhythm`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table107` as SELECT stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.rrt`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table108` as SELECT subject_id, hadm_id, stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.sapsii`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table109` as SELECT subject_id, hadm_id, stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.sapsii`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table110` as SELECT subject_id, stay_id, antibiotic_time as Timestamp FROM `your-project-id1234.x_mimiciv_derived.sepsis3`  where antibiotic_time is not null ;  
create table `your-project-id1234.R_TimeA.Table111` as SELECT subject_id, stay_id, culture_time as Timestamp FROM `your-project-id1234.x_mimiciv_derived.sepsis3`  where culture_time is not null ;  
create table `your-project-id1234.R_TimeA.Table112` as SELECT subject_id, stay_id, suspected_infection_time as Timestamp FROM `your-project-id1234.x_mimiciv_derived.sepsis3`  where suspected_infection_time is not null ;  
create table `your-project-id1234.R_TimeA.Table113` as SELECT subject_id, stay_id, sofa_time as Timestamp FROM `your-project-id1234.x_mimiciv_derived.sepsis3`  where sofa_time is not null ;  
create table `your-project-id1234.R_TimeA.Table114` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.sofa`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table115` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.sofa`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table116` as SELECT subject_id, hadm_id, stay_id, antibiotic_time as Timestamp FROM `your-project-id1234.x_mimiciv_derived.suspicion_of_infection`  where antibiotic_time is not null ;  
create table `your-project-id1234.R_TimeA.Table117` as SELECT subject_id, hadm_id, stay_id, suspected_infection_time as Timestamp FROM `your-project-id1234.x_mimiciv_derived.suspicion_of_infection`  where suspected_infection_time is not null ;  
create table `your-project-id1234.R_TimeA.Table118` as SELECT subject_id, hadm_id, stay_id, culture_time as Timestamp FROM `your-project-id1234.x_mimiciv_derived.suspicion_of_infection`  where culture_time is not null ;  
create table `your-project-id1234.R_TimeA.Table119` as SELECT stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.urine_output`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table120` as SELECT stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.urine_output_rate`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table121` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.vasoactive_agent`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table122` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.vasoactive_agent`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table123` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.vasopressin`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table124` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.vasopressin`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table125` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.ventilation`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table126` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.ventilation`  where endtime is not null ;  
create table `your-project-id1234.R_TimeA.Table127` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.ventilator_setting`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table128` as SELECT subject_id, stay_id, charttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.vitalsign`  where charttime is not null ;  
create table `your-project-id1234.R_TimeA.Table129` as SELECT stay_id, starttime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.weight_durations`  where starttime is not null ;  
create table `your-project-id1234.R_TimeA.Table130` as SELECT stay_id, endtime as Timestamp FROM `your-project-id1234.x_mimiciv_derived.weight_durations`  where endtime is not null ;  




alter table `your-project-id1234.R_TimeA.Table001`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table002`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table003`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table004`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table005`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table006`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table007`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table008`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table009`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table010`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table011`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table012`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table013`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table014`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table015`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table016`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table017`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table018`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table019`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table020`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table021`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table022`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table023`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table024`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table025`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table026`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table027`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table028`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table029`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table030`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table031`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table032`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table033`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table034`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table035`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table036`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table037`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table038`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table039`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table040`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table041`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table042`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table043`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table044`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table045`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table046`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table047`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table048`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table049`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table050`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table051`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table052`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table053`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table054`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table055`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table056`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table057`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table058`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table059`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table060`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table061`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table062`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table063`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table064`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table065`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table066`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table067`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table068`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table069`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table070`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table071`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table072`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table073`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table074`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table075`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table076`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table077`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table078`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table079`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table080`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table081`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table082`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table083`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table084`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table085`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table086`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table087`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table088`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table089`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table090`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table091`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table092`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table093`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table094`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table095`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table096`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table097`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table098`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table099`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table100`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table101`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table102`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table103`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table104`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table105`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table106`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table107`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table108`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table109`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table110`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table111`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table112`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table113`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table114`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table115`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table116`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table117`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table118`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table119`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table120`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table121`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table122`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table123`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table124`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table125`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table126`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table127`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table128`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table129`  add column Title String;
alter table `your-project-id1234.R_TimeA.Table130`  add column Title String;



update `your-project-id1234.R_TimeA.Table001`   set Title="Admissions_edregtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table002`   set Title="Admissions_admittime"    where Title is null;
update `your-project-id1234.R_TimeA.Table003`   set Title="Admissions_edouttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table004`   set Title="Admissions_dischtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table005`   set Title="Admissions_deathtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table006`   set Title="cptEvents_chartdate"    where Title is null;
update `your-project-id1234.R_TimeA.Table007`   set Title="icdPCM_chartdate"    where Title is null;
update `your-project-id1234.R_TimeA.Table008`   set Title="eMAR_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table009`   set Title="eMAR_scheduletime"    where Title is null;
update `your-project-id1234.R_TimeA.Table010`   set Title="eMAR_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table011`   set Title="Microbiology_chartdate"    where Title is null;
update `your-project-id1234.R_TimeA.Table012`   set Title="Microbiology_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table013`   set Title="Microbiology_storedate"    where Title is null;
update `your-project-id1234.R_TimeA.Table014`   set Title="Microbiology_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table015`   set Title="OMR_chartdate"    where Title is null;
update `your-project-id1234.R_TimeA.Table016`   set Title="Patient_dod"    where Title is null;
update `your-project-id1234.R_TimeA.Table017`   set Title="pharmacy_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table018`   set Title="pharmacy_stoptime"    where Title is null;
update `your-project-id1234.R_TimeA.Table019`   set Title="pharmacy_entertime"    where Title is null;
update `your-project-id1234.R_TimeA.Table020`   set Title="pharmacy_verifiedtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table021`   set Title="POE_ordertime"    where Title is null;
update `your-project-id1234.R_TimeA.Table022`   set Title="Blood_Gas_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table023`   set Title="Blood_Gas_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table024`   set Title="Chemistry_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table025`   set Title="Chemistry_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table026`   set Title="Hematology_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table027`   set Title="Hematology_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table028`   set Title="Service_transfertime"    where Title is null;
update `your-project-id1234.R_TimeA.Table029`   set Title="Transfer_intime"    where Title is null;
update `your-project-id1234.R_TimeA.Table030`   set Title="Transfer_outtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table031`   set Title="prescriptions_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table032`   set Title="prescriptions_stoptime"    where Title is null;
update `your-project-id1234.R_TimeA.Table033`   set Title="chartEvent_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table034`   set Title="chartEvent_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table035`   set Title="datetimeEvent_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table036`   set Title="datetimeEvent_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table037`   set Title="datetimeEvent_value"    where Title is null;
update `your-project-id1234.R_TimeA.Table038`   set Title="icuStays_intime"    where Title is null;
update `your-project-id1234.R_TimeA.Table039`   set Title="icuStays_outtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table040`   set Title="ingredientEvent_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table041`   set Title="ingredientEvent_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table042`   set Title="ingredientEvent_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table043`   set Title="inputEvent_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table044`   set Title="inputEvent_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table045`   set Title="inputEvent_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table046`   set Title="outputEvent_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table047`   set Title="outputEvent_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table048`   set Title="procedureEvent_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table049`   set Title="procedureEvent_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table050`   set Title="procedureEvent_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table051`   set Title="discharge_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table052`   set Title="discharge_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table053`   set Title="radiology_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table054`   set Title="radiology_storetime"    where Title is null;
update `your-project-id1234.R_TimeA.Table055`   set Title="edstays_intime"    where Title is null;
update `your-project-id1234.R_TimeA.Table056`   set Title="edstays_outtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table057`   set Title="medrecon_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table058`   set Title="pyxis_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table059`   set Title="vitalsign_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table060`   set Title="age_admittime"    where Title is null;
update `your-project-id1234.R_TimeA.Table061`   set Title="antibiotic_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table062`   set Title="antibiotic_stoptime"    where Title is null;
update `your-project-id1234.R_TimeA.Table063`   set Title="bg_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table064`   set Title="blood_differential_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table065`   set Title="cardiac_marker_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table066`   set Title="chemistry_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table067`   set Title="coagulation_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table068`   set Title="complete_blood_count_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table069`   set Title="crrt_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table070`   set Title="differential_detailed_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table071`   set Title="dobutamine_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table072`   set Title="dobutamine_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table073`   set Title="dopamine_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table074`   set Title="dopamine_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table075`   set Title="enzyme_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table076`   set Title="epinephrine_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table077`   set Title="epinephrine_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table078`   set Title="gcs_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table079`   set Title="height_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table080`   set Title="icp_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table081`   set Title="icustay_detail_dod"    where Title is null;
update `your-project-id1234.R_TimeA.Table082`   set Title="icustay_detail_admittime"    where Title is null;
update `your-project-id1234.R_TimeA.Table083`   set Title="icustay_detail_dischtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table084`   set Title="icustay_detail_icu_intime"    where Title is null;
update `your-project-id1234.R_TimeA.Table085`   set Title="icustay_detail_icu_outtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table086`   set Title="icustay_hourly_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table087`   set Title="icustay_times_intime_hr"    where Title is null;
update `your-project-id1234.R_TimeA.Table088`   set Title="icustay_times_outtime_hr"    where Title is null;
update `your-project-id1234.R_TimeA.Table089`   set Title="inflammation_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table090`   set Title="invasive_line_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table091`   set Title="invasive_line_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table092`   set Title="kdigo_creatinine_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table093`   set Title="kdigo_stages_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table094`   set Title="kdigo_uo_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table095`   set Title="milrinone_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table096`   set Title="milrinone_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table097`   set Title="neuroblock_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table098`   set Title="neuroblock_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table099`   set Title="norepinephrine_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table100`   set Title="norepinephrine_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table101`   set Title="norepinephrine_equivalent_dose_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table102`   set Title="norepinephrine_equivalent_dose_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table103`   set Title="oxygen_delivery_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table104`   set Title="phenylephrine_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table105`   set Title="phenylephrine_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table106`   set Title="rhythm_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table107`   set Title="rrt_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table108`   set Title="sapsii_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table109`   set Title="sapsii_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table110`   set Title="sepsis3_antibiotic_time"    where Title is null;
update `your-project-id1234.R_TimeA.Table111`   set Title="sepsis3_culture_time"    where Title is null;
update `your-project-id1234.R_TimeA.Table112`   set Title="sepsis3_suspected_infection_time"    where Title is null;
update `your-project-id1234.R_TimeA.Table113`   set Title="sepsis3_sofa_time"    where Title is null;
update `your-project-id1234.R_TimeA.Table114`   set Title="sofa_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table115`   set Title="sofa_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table116`   set Title="suspicion_of_infection_antibiotic_time"    where Title is null;
update `your-project-id1234.R_TimeA.Table117`   set Title="suspicion_of_infection_suspected_infection_time"    where Title is null;
update `your-project-id1234.R_TimeA.Table118`   set Title="suspicion_of_infection_culture_time"    where Title is null;
update `your-project-id1234.R_TimeA.Table119`   set Title="urine_output_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table120`   set Title="urine_output_rate_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table121`   set Title="vasoactive_agent_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table122`   set Title="vasoactive_agent_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table123`   set Title="vasopressin_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table124`   set Title="vasopressin_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table125`   set Title="ventilation_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table126`   set Title="ventilation_endtime"    where Title is null;
update `your-project-id1234.R_TimeA.Table127`   set Title="ventilator_setting_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table128`   set Title="vitalsign_charttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table129`   set Title="weight_durations_starttime"    where Title is null;
update `your-project-id1234.R_TimeA.Table130`   set Title="weight_durations_endtime"    where Title is null;


'''

QUERY = (query1)

query_job = client.query(QUERY)  # API request
print(query_job)

for row in query_job.result():
    print(row)
